# Generated by Django 5.0 on 2023-12-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
