# Generated by Django 5.0 on 2023-12-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0003_user_delete_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
