# Generated by Django 5.0 on 2023-12-08 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='line1',
            new_name='line1_address',
        ),
    ]
