# Generated by Django 5.0 on 2023-12-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0006_alter_user_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
