# Generated by Django 5.0 on 2023-12-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0007_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
    ]
