# Generated by Django 5.0 on 2023-12-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0008_rename_user_profile_alter_profile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('password', models.CharField(default=True, max_length=20)),
                ('line1_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='Patient',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
