# Generated by Django 5.0 on 2023-12-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATG', '0010_doctor_user_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
